// Verilog netlist generated by Workcraft 3
// * Workcraft version:  3.4.1
// * Operating system:   Windows 11 amd64
// * Creation timestamp: 2023-12-27T13:48:21.481-03:00
// * Design title:       wxc
// * JavaScript command: framework.exportWork(workspaceEntry, 'wxc.circuit.tech.v', 'Verilog')
module wxc (ctrl, san1, san2, win1, win2, rst_n, g1, g2, wctrl1, wctrl2);
    input ctrl, san1, san2, win1, win2, rst_n;
    output g1, g2, wctrl1, wctrl2;
    wire IN_BUBBLE3_ON, U4_ON, IN_BUBBLE6_ON, U7_ON, U9_O, OUT_BUBBLE12_ON, U13_ON, U14_Q, g0_ON;

    C2 U0 (.Q(g1), .A(ctrl), .B(win1));
    C2 U1 (.Q(g2), .A(ctrl), .B(win2));
    // This inverter should have a short delay
    INV IN_BUBBLE3 (.ON(IN_BUBBLE3_ON), .I(san2));
    OAI21 U4 (.ON(U4_ON), .A1(IN_BUBBLE3_ON), .A2(g2), .B(U14_Q));
    // This inverter should have a short delay
    INV IN_BUBBLE6 (.ON(IN_BUBBLE6_ON), .I(san1));
    OAI21 U7 (.ON(U7_ON), .A1(IN_BUBBLE6_ON), .A2(g1), .B(U14_Q));
    AND2 U9 (.O(U9_O), .A(san2), .B(san1));
    INV OUT_BUBBLE12 (.ON(OUT_BUBBLE12_ON), .I(U13_ON));
    NOR4B U13 (.ON(U13_ON), .AN(ctrl), .B(g2), .C(san1), .D(g1));
    C2 U14 (.Q(U14_Q), .A(g0_ON), .B(OUT_BUBBLE12_ON));
    NAND2B g0 (.ON(g0_ON), .AN(U9_O), .B(rst_n));
    AND2 g3 (.A(U4_ON), .B(rst_n), .O(wctrl1));
    AND2 g4 (.A(U7_ON), .B(rst_n), .O(wctrl2));

    // signal values at the initial state:
    // IN_BUBBLE3_ON IN_BUBBLE6_ON OUT_BUBBLE12_ON !U13_ON U14_Q !U4_ON !U7_ON !U9_O !ctrl g0_ON !g1 !g2 !rst_n !san1 !san2 !wctrl1 !wctrl2 !win1 !win2
endmodule
