// Verilog netlist generated by Workcraft 3
// * Workcraft version:  3.4.1
// * Operating system:   Windows 11 amd64
// * Creation timestamp: 2023-12-27T14:49:35.945-03:00
// * Design title:       WAITX2_control
// * JavaScript command: framework.exportWork(workspaceEntry, 'WAITX2_control.circuit.tech.v', 'Verilog')
module WAITX2_control (xg1, xg2, ctrl, san1, san2, rst_n, g1, g2, xctrl, wctrl1, wctrl2);
    input xg1, xg2, ctrl, san1, san2, rst_n;
    output g1, g2, xctrl, wctrl1, wctrl2;
    wire IN_BUBBLE1_ON, IN_BUBBLE4_ON;

    NOR2B IN_BUBBLE1 (.ON(IN_BUBBLE1_ON), .B(san1), .AN(rst_n));
    C2 U2 (.Q(g1), .A(xg1), .B(IN_BUBBLE1_ON));
    NOR2B IN_BUBBLE4 (.ON(IN_BUBBLE4_ON), .B(san2), .AN(rst_n));
    C2 U5 (.Q(g2), .A(xg2), .B(IN_BUBBLE4_ON));
    NOR3B U6 (.ON(xctrl), .AN(ctrl), .B(g1), .C(g2));
    NOR2B U7 (.ON(wctrl1), .AN(g1), .B(ctrl));
    NOR2B U8 (.ON(wctrl2), .AN(g2), .B(ctrl));

    // signal values at the initial state:
    // !IN_BUBBLE1_ON !IN_BUBBLE4_ON !ctrl !g1 !g2 !rst_n !san1 !san2 !wctrl1 !wctrl2 !xctrl !xg1 !xg2
endmodule
