// Verilog netlist generated by Workcraft 3
// * Workcraft version:  3.4.1
// * Operating system:   Windows 11 amd64
// * Creation timestamp: 2023-12-27T10:15:04.834-03:00
// * Design title:       w2c
// * JavaScript command: framework.exportWork(workspaceEntry, 'w2c.circuit.tech.v', 'Verilog')
module w2c (ctrl, san0, san1, rst_n, san, ctrl0, ctrl1);
    input ctrl, san0, san1, rst_n;
    output san, ctrl0, ctrl1;
    wire IN_BUBBLE1_ON, g0_O, g1_O;

    // This inverter should have a short delay
    INV IN_BUBBLE1 (.ON(IN_BUBBLE1_ON), .I(san0));
    C2 U2 (.Q(san), .A(g0_O), .B(g1_O));
    NOR2B U3 (.ON(ctrl0), .AN(san), .B(ctrl));
    NOR2B U4 (.ON(ctrl1), .AN(ctrl), .B(san));
    AND2 g0 (.O(g0_O), .A(IN_BUBBLE1_ON), .B(rst_n));
    AND2 g1 (.O(g1_O), .A(san1), .B(rst_n));

    // signal values at the initial state:
    // IN_BUBBLE1_ON !ctrl !ctrl0 !ctrl1 !g0_O !g1_O !rst_n !san !san0 !san1
endmodule
