// Verilog netlist generated by Workcraft 3
// * Workcraft version:  3.4.1
// * Operating system:   Windows 11 amd64
// * Creation timestamp: 2023-12-28T11:28:00.601-03:00
// * Design title:       WAIT2_control
// * JavaScript command: framework.exportWork(workspaceEntry, 'WAIT2_control.circuit.v', 'Verilog')
module WAIT2_control (ctrl, san0, san1, rst_n, san, ctrl0, ctrl1);
    input ctrl, san0, san1, rst_n;
    output san, ctrl0, ctrl1;
    wire sana;

    assign sana = (san | san1) & ~san0 | san & san1;
    assign ctrl0 = ~ctrl & san;
    assign ctrl1 = ctrl & ~san;
    assign san = sana & rst_n;

    // signal values at the initial state:
    // !ctrl !ctrl0 !ctrl1 !rst_n !san !san0 !san1 !sana
endmodule
