// Verilog netlist generated by Workcraft 3
// * Workcraft version:  3.4.1
// * Operating system:   Windows 11 amd64
// * Creation timestamp: 2023-12-28T11:34:24.53-03:00
// * Design title:       WAITX_control
// * JavaScript command: framework.exportWork(workspaceEntry, 'WAITX_control.circuit.v', 'Verilog')
module WAITX_control (ctrl, san1, san2, win1, win2, rst_n, g1, g2, wctrl1, wctrl2);
    input ctrl, san1, san2, win1, win2, rst_n;
    output g1, g2, wctrl1, wctrl2;
    wire wctrl1a, wctrl2a, csc, g4;

    assign g1 = ctrl & g1 | win1;
    assign g2 = ctrl & g2 | win2;
    assign wctrl1a = ~g2 & san2 | ~g4;
    assign wctrl2a = ~g1 & san1 | ~g4;
    assign csc = (~ctrl | g1 | g2) & g4 | san1 & san2;
    assign wctrl1 = wctrl1a & rst_n;
    assign wctrl2 = wctrl2a & rst_n;
    assign g4 = ~(~csc & rst_n);

    // signal values at the initial state:
    // csc !ctrl !g1 !g2 g4 !rst_n !san1 !san2 !wctrl1 !wctrl1a !wctrl2 !wctrl2a !win1 !win2
endmodule
