// Verilog netlist generated by Workcraft 3
// * Workcraft version:  3.4.1
// * Operating system:   Windows 11 amd64
// * Creation timestamp: 2023-12-28T11:36:39.804-03:00
// * Design title:       WAITX2_control
// * JavaScript command: framework.exportWork(workspaceEntry, 'WAITX2_control.circuit.v', 'Verilog')
module WAITX2_control (xg1, xg2, ctrl, san1, san2, rst_n, g1, g2, xctrl, wctrl1, wctrl2);
    input xg1, xg2, ctrl, san1, san2, rst_n;
    output g1, g2, xctrl, wctrl1, wctrl2;
    wire g1a, g2a;

    assign g1a = (g1 | ~san1) & xg1 | g1 & ~san1;
    assign g2a = (g2 | ~san2) & xg2 | g2 & ~san2;
    assign xctrl = ctrl & ~g1 & ~g2;
    assign wctrl1 = ~ctrl & g1;
    assign wctrl2 = ~ctrl & g2;
    assign g1 = g1a & rst_n;
    assign g2 = g2a & rst_n;

    // signal values at the initial state:
    // !ctrl !g1 !g1a !g2 !g2a !rst_n !san1 !san2 !wctrl1 !wctrl2 !xctrl !xg1 !xg2
endmodule
